In [1]:
import torch
import torch.nn as nn

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 37,  88,  81, -53,  88, -94])

<br>Making a tensor

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,0.2],[4.2,3.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 0.2000],
        [4.2000, 3.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[ 0.0000e+00,  0.0000e+00,  2.1019e-44],
        [ 0.0000e+00, -8.7155e-05,  5.3810e-43]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=1, end=10, steps=5)
logspace

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye
# Basically I

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<br><br>Some Important Torch Functions

In [11]:
import torch
import numpy as np


<br>"torch.multinomial"

In [12]:
# Define a probability tensor
prob = torch.tensor([0.1,0.9])
# 10% chance of 0
# 90% chance of 1

samples = torch.multinomial(prob, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 0, 0, 1, 0, 1, 1, 1])

<br>"torch.cat" --> concatenate

In [13]:
tensor = torch.tensor([1,2,3])
out = torch.cat((tensor,torch.tensor([4,5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

<br>
"torch.tril" lower triangle

In [14]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

<br>"torch.triu" upper triangle

In [15]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

<br>" .masked_fill" basically exponentiating

In [16]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [17]:
torch.exp(out) # e raised to

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

<br>"torch.transpose"

In [18]:
inp = torch.zeros(2,3,4)
out = inp.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

<br> "torch.stack"

In [19]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked = torch.stack([tensor1, tensor2, tensor3])
stacked

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

<br> nn module and nn.linear and nn.functional

In [20]:
import torch.nn as nn
sample = torch.tensor([19.,19.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ 8.5219, -1.7987, -5.9876], grad_fn=<SqueezeBackward4>)


In [21]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_op = F.softmax(tensor1, dim=0)
softmax_op


tensor([0.0900, 0.2447, 0.6652])

<br>Creating an embedding layer

In [22]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


<br>Matrix Multiplication

In [23]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [24]:
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [25]:
# In Pytorch you cannot multiply different dtypes

int_64 = torch.randint(1,(3,2))
float_32 = torch.rand(2,3)

result = torch.matmul(int_64, float_32)
result

RuntimeError: expected scalar type Long but found Float

In [26]:
a = torch.rand(2,3,5)
# Initialize a tensor of shape 2,3,5

x, y, z = a.shape
# Unpack those dimensions x=2, y=3, z=5

a = a.view(x,y,z)
# Remake the tensor with those dimensions

print(x,y,z)
print(a.shape)

2 3 5
torch.Size([2, 3, 5])
